use chrono::{DateTime, Utc};
use dashmap::DashMap;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::sync::Arc;
use tokio::sync::RwLock;

use crate::orchestrator::HitlRiskLevel;

/// Indicates how the orchestrator should handle failures during plan execution.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanExecutionMode {
    /// Skip failed tasks and continue executing independent tasks if possible.
    BestEffort,
    /// Stop execution immediately if any task fails.
    StopOnFirstError,
    /// Strict dependency execution (similar to StopOnFirstError but can be customized further).
    StrictDag,
}

/// Defines what to do when a specific subtask fails.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FailurePolicy {
    /// Continue executing other independent tasks.
    Continue,
    /// Stop the entire plan.
    StopPlan,
    /// Retry the task up to N times.
    Retry(u32),
}

/// A parsed execution plan generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExecutionPlan {
    pub plan_id: String,
    pub goal: String,
    pub subtasks: Vec<SubTask>,
    pub mode: PlanExecutionMode,
    pub timeout_ms: u64,
    pub created_at: DateTime<Utc>,
}

/// A single step/task within the execution plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubTask {
    pub task_id: String,
    pub description: String,
    pub agent_id: String,
    pub action: String,
    #[serde(default)]
    pub parameters: Value,
    #[serde(default)]
    pub depends_on: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<u64>,
    pub risk_level: HitlRiskLevel,
    #[serde(default = "default_failure_policy")]
    pub on_failure: FailurePolicy,
}

fn default_failure_policy() -> FailurePolicy {
    FailurePolicy::StopPlan
}

/// The current status of a subtask.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SubTaskStatus {
    Pending,
    Running,
    Success,
    Failed,
    Skipped,
    Cancelled,
}

/// The result of executing a subtask.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubTaskResult {
    pub task_id: String,
    pub status: SubTaskStatus,
    pub output: Option<String>,
    pub error: Option<String>,
    pub started_at: Option<DateTime<Utc>>,
    pub finished_at: Option<DateTime<Utc>>,
    pub tokens_used: usize,
}

/// Overall status of the entire plan.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Cancelled,
    PausedForHitl,
}

/// Runtime state of an executing plan.
#[derive(Debug)]
pub struct PlanExecution {
    pub plan: Arc<ExecutionPlan>,
    pub results: Arc<DashMap<String, SubTaskResult>>,
    pub status: Arc<RwLock<PlanStatus>>,
    pub cancel_tx: tokio::sync::watch::Sender<bool>,
}

impl PlanExecution {
    pub fn new(plan: ExecutionPlan) -> Self {
        let (cancel_tx, _) = tokio::sync::watch::channel(false);
        Self {
            plan: Arc::new(plan),
            results: Arc::new(DashMap::new()),
            status: Arc::new(RwLock::new(PlanStatus::Pending)),
            cancel_tx,
        }
    }
}
